package swe

import (
	"fmt"
	"os/exec"
	"strings"
)

// PRContent holds the generated title and body for a pull request.
type PRContent struct {
	Title string
	Body  string
}

// GeneratePRContent builds a PR title and body from the task description,
// a diff summary, and the number of TDD iterations performed.
// It is pure string manipulation — no LLM call, no side effects.
func GeneratePRContent(task, diffSummary string, iterations int) (title, body string) {
	// Title: first non-empty sentence of the task, capped at 72 chars.
	title = buildTitle(task)

	// Body: structured markdown.
	var sb strings.Builder
	sb.WriteString("## Summary\n\n")
	sb.WriteString(task)
	sb.WriteString("\n\n")
	if diffSummary != "" {
		sb.WriteString("## Changes\n\n")
		sb.WriteString(diffSummary)
		sb.WriteString("\n\n")
	}
	sb.WriteString(fmt.Sprintf("## Meta\n\n- TDD iterations: %d\n- Generated by: hera-swe\n", iterations))
	body = sb.String()
	return title, body
}

// buildTitle extracts the first sentence from task, strips trailing punctuation,
// and caps the result at 72 characters.
func buildTitle(task string) string {
	task = strings.TrimSpace(task)
	// Split on sentence boundaries.
	for _, sep := range []string{". ", ".\n", "\n"} {
		if idx := strings.Index(task, sep); idx > 0 {
			task = task[:idx]
			break
		}
	}
	// Replace newlines with spaces.
	task = strings.ReplaceAll(task, "\n", " ")
	// Strip trailing punctuation.
	task = strings.TrimRight(task, ".!?")
	task = strings.TrimSpace(task)
	if len(task) > 72 {
		task = task[:72]
	}
	return task
}

// CreatePR invokes `gh pr create` with the given title and body.
// It returns an error if gh is not found in PATH or if the command fails.
func CreatePR(title, body string) error {
	ghPath, err := exec.LookPath("gh")
	if err != nil {
		return fmt.Errorf("gh CLI not found in PATH: install the GitHub CLI (https://cli.github.com) to use -pr")
	}
	cmd := exec.Command(ghPath, "pr", "create", "--title", title, "--body", body)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("gh pr create failed: %w\noutput: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
